App\SiteBundle\Entity\Artist:
    type: entity
    table: artists
    repositoryClass: App\SiteBundle\Repository\ArtistRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            unsigned: true
    fields:
        name:
            type: string
            length: 150
        cardCount:
            type: integer
            unsigned: true
            nullable: true
            column: card_count