App\SiteBundle\Entity\Set:
    type: entity
    table: sets
    repositoryClass: App\SiteBundle\Repository\SetRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            unsigned: true
    fields:
        name:
            type: string
            length: 150
        slug:
            type: string
            length: 150
        code:
            type: string
            length: 3
        releaseDate:
            column: release_date
            type: date
        synchronized:
            type: datetime
            nullable: true
        cardCount:
            column: card_count
            type: integer
            unsigned: true
        promo:
            type: boolean
    manyToOne:
        block:
            targetEntity: Block
        type:
            targetEntity: Type