parameters:
    database_driver: pdo_mysql
    database_host: 192.168.2.203
    database_port:
    database_name: wesley_personal
    database_user: freshheads
    database_password: ypo73mpv
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: cd8f352110b2aa8f1397dbd381ddf9247
    database_path: null
