parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port:
    database_name: magic
    database_user: root
    database_password:
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: cd8f352110b2aa8f1397dbd381ddf9247
    database_path: null
